const {By} = require("selenium-webdriver")
const assert = require("assert")

class CheckoutPage{
    constructor (driver){
        this.driver = driver;
        this.fnameField = By.id()
        this.lnameField = By.id()
        this.emailField = By.id()
        this.companyDropdown = By.id()
        this.stateDropdown = By.id()
        this.cityField = By.id()
        this.address1Field = By.id()
        this.address2Field = By.id()
        this.zipField = By.id()
        this.phoneField = By.id()
        this.faxField = By.id()
        this.continueStep1 = By.id()
        this.shpAddressField = By.id("shipping-address-select")
        this.inStorePickupCBox = By.id()
        this.backBtnStep2 = By.xpath("")
        this.continueStep2 = By.id("")
        this.nextdayShp = By.xpath("//input[@value='Next Day Air___Shipping.FixedRate']")
        this.backBtnStep3 = By.xpath("")
        this.continueStep3 = By.id("")
        this.poRadioBtn = By.xpath()
        this.backBtnStep4 = By.xpath("")
        this.continueStep4 = By.id("")
        this.poNumberField = By.id("PurchaseOrderNumber")
        this.backBtnStep5 = By.xpath("")
        this.continueStep5 = By.id("")
        this.backBtnStep6 = By.xpath("")
        this.continueStep6 = By.id("")
        this.successCheckout = By.css("strong")
        this.detailOrderTextLink = By.xpath("//a[.='Click here for order details.']")
        this.continueBtn = By.css(".button-2")
        this.downloadBtn = By.css(".pdf-order-button")
        this.printBtn = By.css(".print-order-button")
        this.reorderBtn = By.css(".re-order-button")
    }
}